# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\vscode-\test\可视计算\final-vcl\mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.choose_action = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\vscode-\\test\\可视计算\\final-vcl\\Icon/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.choose_action.setIcon(icon)
        self.choose_action.setObjectName("choose_action")
        self.open_action = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\vscode-\\test\\可视计算\\final-vcl\\Icon/Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_action.setIcon(icon1)
        self.open_action.setObjectName("open_action")
        self.save_action = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\vscode-\\test\\可视计算\\final-vcl\\Icon/saving.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_action.setIcon(icon2)
        self.save_action.setObjectName("save_action")
        self.color_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\vscode-\\test\\可视计算\\final-vcl\\Icon/board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.color_action.setIcon(icon3)
        self.color_action.setObjectName("color_action")
        self.toolBar.addAction(self.open_action)
        self.toolBar.addAction(self.save_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.choose_action)
        self.toolBar.addAction(self.color_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.choose_action.setText(_translate("MainWindow", "选择"))
        self.open_action.setText(_translate("MainWindow", "打开"))
        self.open_action.setToolTip(_translate("MainWindow", "新建"))
        self.save_action.setText(_translate("MainWindow", "保存"))
        self.color_action.setText(_translate("MainWindow", "取色"))
#import img_rcc_rc
