# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'line_in.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_line_Form(object):
    def setupUi(self, line_Form):
        line_Form.setObjectName("line_Form")
        line_Form.resize(180, 160)
        self.gridLayout = QtWidgets.QGridLayout(line_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(line_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.x0 = QtWidgets.QLineEdit(line_Form)
        self.x0.setObjectName("x0")
        self.horizontalLayout.addWidget(self.x0)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(line_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.y0 = QtWidgets.QLineEdit(line_Form)
        self.y0.setObjectName("y0")
        self.horizontalLayout_2.addWidget(self.y0)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(line_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.x1 = QtWidgets.QLineEdit(line_Form)
        self.x1.setObjectName("x1")
        self.horizontalLayout_3.addWidget(self.x1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(line_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.y1 = QtWidgets.QLineEdit(line_Form)
        self.y1.setObjectName("y1")
        self.horizontalLayout_4.addWidget(self.y1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ok_btn = QtWidgets.QPushButton(line_Form)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_5.addWidget(self.ok_btn)
        self.re_btn = QtWidgets.QPushButton(line_Form)
        self.re_btn.setObjectName("re_btn")
        self.horizontalLayout_5.addWidget(self.re_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(line_Form)
        self.re_btn.clicked.connect(self.x0.clear)
        self.re_btn.clicked.connect(self.y0.clear)
        self.re_btn.clicked.connect(self.x1.clear)
        self.re_btn.clicked.connect(self.y1.clear)
        QtCore.QMetaObject.connectSlotsByName(line_Form)

    def retranslateUi(self, line_Form):
        _translate = QtCore.QCoreApplication.translate
        line_Form.setWindowTitle(_translate("line_Form", "参数输入"))
        self.label.setText(_translate("line_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">起点</span><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.label_2.setText(_translate("line_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">起点</span><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.label_3.setText(_translate("line_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">终点</span><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.label_4.setText(_translate("line_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">终点</span><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.ok_btn.setText(_translate("line_Form", "确定"))
        self.re_btn.setText(_translate("line_Form", "重置"))

