# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'round_in.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_round_Form(object):
    def setupUi(self, round_Form):
        round_Form.setObjectName("round_Form")
        round_Form.resize(180, 127)
        self.gridLayout = QtWidgets.QGridLayout(round_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(round_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(round_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(round_Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(round_Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(round_Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(round_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.x0 = QtWidgets.QLineEdit(round_Form)
        self.x0.setObjectName("x0")
        self.verticalLayout_2.addWidget(self.x0)
        self.y0 = QtWidgets.QLineEdit(round_Form)
        self.y0.setObjectName("y0")
        self.verticalLayout_2.addWidget(self.y0)
        self.R = QtWidgets.QLineEdit(round_Form)
        self.R.setObjectName("R")
        self.verticalLayout_2.addWidget(self.R)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ok_btn = QtWidgets.QPushButton(round_Form)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_2.addWidget(self.ok_btn)
        self.re_btn = QtWidgets.QPushButton(round_Form)
        self.re_btn.setObjectName("re_btn")
        self.horizontalLayout_2.addWidget(self.re_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(round_Form)
        self.re_btn.clicked.connect(self.x0.clear)
        self.re_btn.clicked.connect(self.y0.clear)
        self.re_btn.clicked.connect(self.R.clear)
        QtCore.QMetaObject.connectSlotsByName(round_Form)

    def retranslateUi(self, round_Form):
        _translate = QtCore.QCoreApplication.translate
        round_Form.setWindowTitle(_translate("round_Form", "参数输入"))
        self.label.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">X</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">圆心</span></p></body></html>"))
        self.label_2.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Y</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">圆心</span></p></body></html>"))
        self.label_3.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">R</span><span style=\" font-size:10pt; font-weight:600; vertical-align:sub;\">半径</span></p></body></html>"))
        self.label_4.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.label_5.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.label_6.setText(_translate("round_Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">：</span></p></body></html>"))
        self.ok_btn.setText(_translate("round_Form", "确定"))
        self.re_btn.setText(_translate("round_Form", "重置"))

